volumes:
    redis-volume:
    postgres-volume:

networks:
    people-api-network:
        driver: bridge

services:

    db:
        image: postgres:17.0
        container_name: "people-api-database"
        env_file:
            - .env
        networks:
            - people-api-network
        ports:
            - $POSTGRES_PORT:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 1s
            timeout: 60s
            retries: 60
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    redis:
        image: redis:alpine3.19
        container_name: "people-api-redis"
        env_file:
            -   .env
        ports:
            -   $REDIS_PORT:6379
        networks:
            people-api-network:
        volumes:
            -   redis-volume:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1s
            timeout: 60s
            retries: 5